name: LeaguePlugin
version: '${version}'
main: me.oliverhesse.leagueplugin.LeaguePlugin
api-version: '1.20'
depend:
  - ProtocolLib
commands:
  spawn:
    description: spawns a custom mob
    usage: /spawn
  setDest:
    description: spawns a custom mob
    usage: /setDest
  setSpawn:
    description: spawns a custom mob
    usage: /setSpawn
